### PR TITLE
LDAP Support

### PR DESCRIPTION
**Pull request by skipfire**
Config file editing only based on the conversation about insecure logins.  Supports admin & read only groups.  The single-accounts still work with LDAP enabled.  The additional import is also wrapped in error handling and only happens if ldap_server is specified in the config.

### CODE REVIEW

**Comment by skipfire** [comment]
The initial diff is really not happy for some reason, add the w=1 to trim it down to the real changes.

**Comment by jgyates** [comment]
I don't know what you mean by "add the w=1"

**Comment by skipfire** [comment]
@jgyates if you have a github review that is showing a massive volume of edit that didn't happen, you can add a query parameter of w=1 and it will ignore whitespace.  I did the edits on the Pi, so maybe it was a Windows to Linux line ending or something.

https://github.com/jgyates/genmon/pull/396/files?w=1

**Comment by jgyates** [comment]
couple of questions:

1) is python-ldap the only library need for the installation. I can add this to the install scrtipt and genloader.py (loads libraries that are missing but this will install it for all users, even if they do not use this feature. Do you see any issues with this?
2) I will likley add this via pip instead of apt-get since this method is better for cross platform installs. Do you see any issues with this?
2) Looks like you have the LDAP login code for the normal login (/ see root()), but the /low (see lowbandwidth()), /internal (see display_internal()) and /logout  (see logout()) url paths are not implementing this. I can you add your code here as well. There may be an opportunity to consolidate some of the code across root, lowbandwidt and internal.

**Comment by skipfire** [comment]
1. I do not see any potential issues with installing the python-ldap library for everyone.  I tested both with and without it installed.
2. I don't know of any problems from installing it with pip.  Still new to python (this is my first for python) so I don't have a good knowledge of what pip does.
3. You are correct about not having anything in the low or logout.  Logout was an oversight as I did not test the case of not having the current admin account added.  The low I don't see any username validation, that only seemed to be in the do-admin..

**Comment by jgyates** [comment]
Here is some background on pip: https://docs.python.org/3/installing/index.html

I think your are correct about the low, and internal, it has been a while since I have looked at that code.

Can you validate you can logout with your ldap changes  https://ipaddress/logout

Also, can you validate this with python3. I would do this but I do not have a ldap server setup.

To do this:

     sudo ./genmonmaint.sh -i -p 3
     ./startgenmon.sh -p 3 restart

I am trying to support python3 as 2.7 will likely to go away as the default soon.

**Comment by skipfire** [comment]
Yeah, I've removed the designated account already and been testing without that, glad you caught it.

**Comment by skipfire** [comment]
@jgyates is there something needed for /low to work?  Trying without my changes fails.

**Comment by jgyates** [comment]
it should just bring up a web page without the gauges or graph. it is intended for low bandwidth connections.  

On my system I access it this way:

     http://192.168.1.14:8000/low

Is the the url you use (assume ip is different)?

**Comment by skipfire** [comment]
I am going by the device name instead of IP, but :8000/low yes.  I'll come back to low after I get everything else tested.

`$ tail /var/log/genserv.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.`

**Comment by skipfire** [comment]
The library itself is not python3 compatible and there is a newer library that is python3 compatible and it is said to be backwards to others, I will have to work on porting to that one.  The other method changes all tested ok before upgrading to python 3.  I'll update this in a day or two for the newer library after I get it updated and tested on both versions.

**Comment by skipfire** [comment]
@jgyates I got it all working in both Python 3.7.3 and 2.7.16.  I did find that I had to install the module in both using pip & pip3.

**Comment by jgyates** [comment]
Hi @skipfire I will not have a chance to review this until tomorrow evening or Wednesday. Yes there are two separate installs for 2.7 vs 3.x libraries so that is normal. 

Did you ever get the other URLs to respond?

**Comment by skipfire** [comment]
@jgyates everything but /low, which also did not work on a clean setup without my changes.  I'm going to try a fresh install again on a Pi 3 today rather than the Pi 4 that currently has the base install.

**Comment by skipfire** [comment]
@jgyates I found the problem with /low, it doesn't support the login, but once logged in switching to /low works fine.  To the best of my knowledge, it is done and everything works.

**Comment by jgyates** [comment]
V1.14.12 is checked in with these changes merged. Thanks!

**Pull request merged**
