### PR TITLE
chore: Add automatic code formatting

### PR DESCRIPTION
**Pull request by rcmurphy**
# Pull Request Template

## Description

This adds `black`, `isort`, strips trailing spaces, and fixes ends of files.

https://pre-commit.ci/ should be turned on to enforce it.

I left flake8 commented out as there are a _lot_ of issues, but hopefully I can follow up with that soon, and then we'll have linting!

## Type of change

Please delete options that are not relevant.

- [x] Chore

## How Has This Been Tested?

N/A

### CODE REVIEW

**Comment by rcmurphy** [comment]
**Reviewer notes:**
Linting/Formatting Config: 13fb34e
Documentation: 60ac6f4
The application thereof: 926734a

**Comment by jgyates** [comment]
@rcmurphy, thanks! Give me a day or so to digest but at first glance this all looks great. I will let you know if I have any questions.

**Comment by jgyates** [comment]
Hi @rcmurphy,

I have a question regarding the pre-commit hooks. Does this require the installation of pre-commit to checkout and update the repository or is this only needed for committing? I want to validate that this update does not break the software update process. If someone clicks the "Upgrade to the latest version" button on the about page then the following two commands will be executed:

    git fetch origin
    git reset --hard origin/master

Also, this repo is referenced: https://github.com/pre-commit/mirrors-isort however this is marked deprecated. Not knowing anything about what is typical with CI, I am not sure if this is intended. 

One other newbie question: Can your briefly describe how this works. It looks to me that this will automatically formate the code to the predefined standard. Are there any additional steps that I need to take to check in code? Can code be rejected due to failures in the pre-commit rules? This sounds useful, I just want to make sure I know what I am signing up for.

Thanks
Jason

**Comment by rcmurphy** [comment]
Hey! Sorry, day job has been taking the majority of my time this week.

1. Shouldn't be a problem... This is an opt in system that _can_ be installed locally. The only time it will forcibly change something is when you make a PR against repo (if you use pre-commit.ci)... 
2. Didn't realize the isort-mirror was deprecated; nice catch! I was copying the config from an old python project and updated the versions, so it was an oversight. I will switch it to isort now.
3. pre-commit is a binary you can install locally. If you run `pre-commit install`, it will then, on every commit, run these checks against your code before you can commit it. If you commit code and open a PR that doesn't comply, pre-commit.ci will flag it (or fix it if it's a minor issue like trailing whitespace). `black` is a python code formatter, and `isort` just keeps your imports organized.

**Review by jgyates — COMMENTED** [review]
Thanks

**Review by jgyates — APPROVED** [review]
V1.18.15

**Comment by rcmurphy** [comment]
How would you feel about a discord to coordinate development? I’ve seen other open source projects use it to great effect!

**Comment by jgyates** [comment]
I don't have a problem with that. We used one briefly when developing the work around to the Evo2.0 encryption problem. it was an invite only group, but I did not set that up. One for general development may want to be more open. Also, I would want to make sure that the use of discord was not taking anything away from the github issue forum as this is the preferred method of support since each thread can be categorized and searched.

**Comment by rcmurphy** [comment]
💯

If it's ok with you, I'd love to set one up like I've seen in other successful OSS communities. Happy to cede ownership once everything is set up and integrated.

**Comment by jgyates** [comment]
sounds good. Thanks

**Comment by rcmurphy** [comment]
https://discord.gg/FDKbjmvUDa as promised!

**Pull request merged**
