### PR TITLE
Fix LDAP

### PR DESCRIPTION
**Pull request by magomez96**
Remove statically defined search base in code, add support for login with short name, improve error handling

### CODE REVIEW

**Comment by skipfire** [comment]
Will people already using ldap have to change their configs?  I can test these changes on my ldap later today.

**Comment by magomez96** [comment]
Yes, there is one additional config file param:
# (Optional) This parameter is required to use ldap and will look like 
# mydomain
domain_netbios =

That being said, I can't see how this ever worked for anyone whose domain name is not skipfire.local, since 'dc=skipfire,dc=local' was hardcoded in genserv.py on line 183

**Comment by jgyates** [comment]
As far as I know @skipfire was the only one using this. He submitted the mod. I do not use LDAP so I relied on his testing. I am glad you found this.

**Comment by skipfire** [comment]
As am I, I thought I had gotten my stuff scrubbed.

**Comment by magomez96** [comment]
No problem, there's also a couple other things on my to do list. Among them getting rid of auto_bind=True and adding optional config file parameters for a bind user and pass. This will allow login with user accounts that do not have ldap bind permissions. Currently, if the user does not have bind permissions the login will fail

**Comment by skipfire** [comment]
@jgyates this code does work for me once I added the new parameter.

@magomez96 I did not see where the DomainNetbios value is being used but if it isn't set it disables ldap (clears the LdapServer value), am I missing something?  I'm just curious.  I'm also happy to test any ldap improvements you have.  I come from the Mcirosoft world so I'm used to direct to AD rather than LDAP, and I'd not used Python before as I use Java & C# professionally.

**Comment by magomez96** [comment]
@skipfire DomainNetbios is used on line 185 of genserv.py if you don't specify the username in the format of domain\user it will use the value of domain_netbios in the config file for domain

**Pull request merged**
