### PR TITLE
No absolute URLs: Remove leading / from file names.

### PR DESCRIPTION
**Pull request by RalphBSz**
The web-based UI may have to work when embedded (via proxy) into another web server, at a subdirectory. That means all URLs within the html that is served need to be relative, not absolute; that includes URLs served from JS and CSS. Fixed a few instances of URLs that begin with "/images/...".

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:

## Checklist:

- [ ] Are any new libraries required and have they been added to the install scripts
- [ ] My code follows the existing code style and formatting of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reasonably commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or errors
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tested any python code on 3.x
- [ ] I have tested any javascript on most popular browsers for compatibility

### CODE REVIEW

**Comment by jgyates** [comment]
when I tested this it appears to not load the files path that were modified:

Screenshot 2024-01-17 at 4 09 01 PM

I applied the file then ran this command:

cd genmon/static
python3 closeure-compiler.py

Then I loaded genmon / refreshed the browser and looked at developer tools under Network View to see each file that was downloaded.

**Comment by RalphBSz** [comment]
This is what I see in the logs of the web server that's proxying for the generator (from starting the web UI once, filtering the logs for the string "images"):
192.168.0.66 - - [17/Jan/2024:12:17:48 -0800] "GET /generator/images/sprites.png HTTP/1.1" 200 48777
192.168.0.66 - - [17/Jan/2024:12:17:49 -0800] "GET /generator/images/ui-icons_222222_256x240.png HTTP/1.1" 200 7006
192.168.0.66 - - [17/Jan/2024:12:17:49 -0800] "GET /generator/images/transparent.png HTTP/1.1" 200 68

Of those, the one that was giving trouble earlier was the images/ui-icons... one.

**Comment by jgyates** [comment]
Have you tested this locally, without the proxy? This is the way almost every else uses the software.

**Comment by RalphBSz** [comment]
Yes, has been running like this since Sunday. Works fine for local access http://generator....:8000.

**Comment by jgyates** [comment]
did you run closure-compiler.py after you made the changes to your local copy of  ./static/css ?

**Comment by RalphBSz** [comment]
No, on the pull request I did not. Sorry about that; I know you mentioned it a few days ago, but I forgot.

On the working copy, I actually did worse: I edited **both** the source code (jquery-ui...) and the compacted library... version, both by hand. I know that on the next update, I'll have problems merging my local changes ... that can be dealt with.

**Comment by jgyates** [comment]
also, for testing purposes you can use this page:

http://192.168.11.22:8000/index_verbose.html

index_verbose.html will use the compacted versions

**Comment by RalphBSz** [comment]
Sorry for all the delays ... we're having a day with nice weather today, so my son and I are outside planting fruit trees. Anyway, index_verbose.html works excellently too, both directly (generator...:8000/index_verbose.html) and through the proxy (https:/house.../generator/index_verbose.html). And today for the first time I tried the proxy through my secure/secret remote tunnel, and it works there too.

**Review by jgyates — COMMENTED** [review]
OK. It is working now. Not sure what I did wrong before. Thanks for being patient with me. I am not much of a javascript/CSS person

**Pull request merged**
