### PR TITLE
Add HomeAsstant Integration

### PR DESCRIPTION
**Pull request by ajsomething**
Added option in configuration file and genmqtt for automatically telling home assistant of available sensors

### CODE REVIEW

**Comment by ajsomething** [comment]
GUI Option for MQTT addon in Genmon not done yet. Need toggle switch.

**Comment by jgyates** [comment]
@ajsomething, what is the purpose of the code following this comment:

      # post to configuration topics for homeassistant to pick up

I can see the value of having an option to remove spaces in topic name but can you give some context on the other code? I am hesitant to add the rest of the code since removing the root topic is redundant (just don't add one, the default is not blank and dont enable JSON numerics) and the code that posts to configuration topics is specific to only Evolution controllers that use wifi.

**Comment by ajsomething** [comment]
Done, Correct files in correct locations

**Comment by jgyates** [comment]
I am a bit confused on the homeassistant integration. In this thread:

https://github.com/jgyates/genmon/issues/155

Folks asked for the ability to add JSON Numerics for better integration with HA in the above thread, they are also using spaces in topic names.

**Comment by ajsomething** [comment]
Sorry, Didn't see the message. My files were all over the place.....

I'm referencing https://www.home-assistant.io/docs/mqtt/discovery/

Home Assistant listens to the MQTT topic "homeassistant"
When it receives a json formatted configuration on that topic it loads the sensors into the Home Assistant system.
All the configuration is done by those 10 lines of code....  If those lines are not done then they have to be manually put in the home assistant configuration files witch creates some interesting configurations. #155 is one example. 
My Code {"value_template": "{{ value | regex_replace('[^0-9.-]+','') | float }}" }
Replaces the need for the numerics by using Homeassistant to convert the value to a float, and telling it the base of its measurement. (V, KW, F, ... Etc.)

#155 References a configuration that uses extra sensors to bring in the raw json data into home assistant. he then creates additional sensors that reference those to actually show the data. Home assistant is limited to 256 characters of sensor data. His work around however is clever but creates extra sensors that are recorded and take up useless log space to create the child sensors that are displayed and used.

I never understood the Json Numerics and cant see how that useful for home assistant... Home Assistant has the ability to do what he asks without modifying the code to remove V, KW etc...

**Comment by ajsomething** [comment]
Basically my addition is a unification of the workarounds that have been previously implemented, to get the data into HA. The code checking for base topic and numeric was just an attempt to stop combinations that would break the purposed code. I will also be writing up a "How To" for the home assistant community and adding more sensors fore Home Assistant.

I think this is a step towards the "It Just Works out of the box" so many people enjoy

**Comment by ajsomething** [comment]
HA-Dashboard

This automatically creates the sensors in Home Assistant and using Grafana to display history....

**Comment by liltux** [comment]
I haven’t reviewed the code, but the comment “works out of the box” with home assistant?  What will that change for the ones not using home assistant?  I use Node Red and have no issues with the MQTT and it already works out of the box?  Just curious.

**Comment by jgyates** [comment]
The proposed changes should not change the default behavior or alter any existing settings. 

@ajsomething , I am looking into the changes you proposed. My main concern is how this will work on other generators and pi's that do not use wifi. 

I am not opposed to these updates, however I do want to think on them. Whenever an add on or some other code makes references to the underlying structure of how the data is organized it makes me pause as this is a complication for maintenance reasons. I try to minimize the dependencies on the data structures (e.g. specific paths for MQTT topics) as these could change and break other things. The existing MQTT code was written to be agnostic of any topic paths and this update will change that.

**Comment by ajsomething** [comment]
@liltux If the option is turned off, the there are no underlying changes. I have no experience with Node Red, so i can not say what would happen if it was enabled.

@jgyates The extent of the changes are as follows; 
If not enabled - Change nothing
If Enabled - Replace Space with underscore, and when first connected to MQTT publish 10 (as of now) messages over MQTT Then operate as normal (With the exception of not using spaces in any MQTT topics)

How many people will use this feature, Unknown it is solely coded for Home Assistant.
Other negatives - Setting president the specific code will be maintained in a working condition, While I can keep the code working now. HA has a track record of making major breaking changes that render major portions unusable without rewriting intergrations. As an example https://community.home-assistant.io/t/monitor-your-generac-generator-with-home-assistant/62701 does not work without modification. Its only 2 years old.

I would have liked to do this as a completely separate AddOn but the addons are hard coded into the genmon server. would you entertain the idea of moving them to external? providing an API through a socket, and somehow integrating it into the GUI?

My Other options are a completely separate app that does this, but I like the one gui for all.

**Comment by lmamakos** [comment]
I was the perpetrator of the original thread referenced regarding Home Assistant. 

@jgyates an important thing in here is the 'autoconfiguration' message that's published to that well-known MQTT topic.  This allows Home Assistant to automagically generate sensor entities without having to manually construct a bunch of YAML configuation.   It's routine for me to generate all that stuff manually as I use MQTT as the integration technology in Home Assistant for all sorts of external sensors, so no big deal.  However, simply publishing the autoconfiguration message makes it much, much easier for a Home Assistant user.

@ajsomething is there really no way to generate the Home Assistant configuration message that references MQTT topics with embedded spaces?  Certainly topic names with spaces are perfect valid for MQTT sensor entities (and entities of all types, for that matter).  Is this just an issue with autoconfiguration messages that are published?

Also, the `regex_replace()` filters in the jinga2 template seems like it strips out the numeric value by changing them to a null string.. if you have the numeric units thing configured in genmon, I think all you might need to do is `{{ value | float | round(1) }}` for instance.

**Comment by lmamakos** [comment]
> Other negatives - Setting president the specific code will be maintained in a working condition, While I can keep the code working now. HA has a track record of making major breaking changes that render major portions unusable without rewriting intergrations. As an example https://community.home-assistant.io/t/monitor-your-generac-generator-with-home-assistant/62701 does not work without modification. Its only 2 years old.

Just for completeness - the approach referenced here was what I did before MQTT was available in `genmon` and made use of the REST sensor in Home Assistant to bang against the API in `genmon` to extract one large JSON blob.  You wouldn't choose to do this any longer now that the individual data items are each published to their own MQTT topic.

**Comment by ajsomething** [comment]
@lmamakos I tried to just do it with the spaces, HA gave me an error. Very cryptic. I don't remember what it was exactly but removing the spaces resolved it.... And the regex_replace() replaces all non numeric characters with "" (Removes them) It does however allow "-" and "." ( "240 V" throws an error when float is applied)

**Comment by lmamakos** [comment]
I see what your regexp does now, that looks like it works, though it makes me uneasy, somehow :-)

For the "system in outage" sensor, for completeness you probably should have both `payload_on` and `payload_off` present.

Just as reference, here's what I have manually configured for the entities that I use.  Note that there are a few classes of MQTT messages that I choose to exclude, so perhaps not 100% complete.

```yaml
sensor:
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    state_topic: '19916/generator/Outage/Status'
    name: Genmon Outage Status

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    state_topic: '19916/generator/Outage/Utility Voltage'
    name: Genmon Outage Utility Voltage
    value_template: '{{ value | regex_replace(" V", "") | float | round(1) }}'
    unit_of_measurement: "VAC"

  # status related sensors
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Battery
    state_topic: '19916/generator/Status/Engine/Battery Voltage'
    unit_of_measurement: "V"
    value_template: '{{ value | regex_replace(" V", "") | float }}'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name:  Genmon Generator RPM
    unit_of_measurement: "RPM"
    state_topic: '19916/generator/Status/Engine/RPM'
    value_template: '{{ value | int }}'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Frequency
    unit_of_measurement: "HZ"
    state_topic: '19916/generator/Status/Engine/Frequency'
    value_template: '{{ value | regex_replace(" Hz","") | float }}'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Output Voltage
    unit_of_measurement: "VAC"
    state_topic: '19916/generator/Status/Engine/Output Voltage'
    value_template: '{{ value | regex_replace(" V","") | float | round(1) }}'

  # current measrement is garbage on 22KW product, apparently
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Output Current
    unit_of_measurement: "A"
    state_topic: '19916/generator/Status/Engine/Output Current'
    value_template: '{{ value | regex_replace(" A","") | float | round(1) }}'
        
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Output Power
    unit_of_measurement: "W"
    state_topic: '19916/generator/Status/Engine/Output Power (Single Phase)'
    # this is normalized to watts from kilowatts
    value_template: '{{ value | regex_replace(" kW","") | float * 1000 | round(0) }}'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Last Alarm Log
    state_topic: '19916/generator/Status/Last Log Entries/Logs/Alarm Log'
        
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Last Service Log
    state_topic: '19916/generator/Status/Last Log Entries/Logs/Service Log'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Last Action
    state_topic: '19916/generator/Status/Last Log Entries/Logs/Start Stop Log'
        
    # maint related sensors
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Capacity
    state_topic: '19916/generator/Maintenance/Rated kW'
    # normalize to watts
    value_template: '{{ value | float * 1000 | round(1) }}'
    unit_of_measurement: 'W'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Generator Exercise Time
    state_topic: '19916/generator/Maintenance/Exercise/Exercise Time'
    # might be nice to maybe somehow normalize this, but not sure into what date/time representation
    # value is something like:  "Weekly Sunday 17:35 Quiet Mode On"

  # genmon monitor related sensors
  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Mon CPU Temperature
    unit_of_measurement: "°F"
    device_class: temperature
    state_topic: '19916/generator/Monitor/Platform Stats/CPU Temperature'
    value_template: '{{ value | regex_replace(" F","") | float | round(1) }}'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Mon Uptime
    # maybe parse this out into minutes/hours?
    state_topic: '19916/generator/Monitor/Platform Stats/System Uptime'

  - platform: mqtt
    expire_after: 300   # genmon MQTT flushes out MQTT updated every 60 seconds
    name: Genmon Mon Load
    unit_of_measurement: '%'
    state_topic: '19916/generator/Monitor/Platform Stats/CPU Utilization'
    value_template: '{{ value | regex_replace(" *%","") | float | round(1) }}'

  - platform: mqtt
    expire_after: 600
    name: Genmon 1W Controller Box
    unit_of_measurement: °F
    state_topic: '19916/generator/Status/External Temperature Sensors/28-00000bc56fa5'
    value_template: '{{ value | regex_replace(" *F", "") | float | round(1) }}'

  - platform: mqtt
    expire_after: 600
    name: Genmon 1W Outside Air
    unit_of_measurement: °F
    state_topic: '19916/generator/Status/External Temperature Sensors/28-020a91770670'
    value_template: '{{ value | regex_replace(" *F", "") | float | round(1) }}'

  - platform: mqtt
    expire_after: 600
    name: Genmon TC Generator Body
    unit_of_measurement: °F
    state_topic: '19916/generator/Status/External Temperature Sensors/3b-6d800cc77f01'
    value_template: '{{ value | regex_replace(" *F", "") | float | round(1) }}'

  - platform: mqtt
    expire_after: 600
    name: Genmon TC Oil Cooler
    unit_of_measurement: °F
    state_topic: '19916/generator/Status/External Temperature Sensors/3b-4c880b6ac367'
    value_template: '{{ value | regex_replace(" *F", "") | float | round(1) }}'

  - platform: mqtt
    expire_after: 600
    name: Genmon TC Engine Body
    unit_of_measurement: °F
    state_topic: '19916/generator/Status/External Temperature Sensors/3b-4c880b6ac389'
    value_template: '{{ value | regex_replace(" *F", "") | float | round(1) }}'

binary_sensor:
  - platform: mqtt
    name: Genmon Power Outage
    state_topic: '19916/generator/Outage/System In Outage'
    payload_on: 'Yes'
    payload_off: 'No'
```

I have patterns to specifically match the units suffix that may be present.  I think this will work even if genmon omits the units when the messages are published, so it doesn't matter how the "JSON numerics" configuration knob is set.

**Comment by ajsomething** [comment]
Please Hold on this Pull request, I am reviewing alternative options (Node-Red, Custom HA Integrations, and others)

This may be easier to implement elsewhere and consume less resources.

**Comment by jgyates** [comment]
ok. let me know what you find. I have added the functionality but have not checked anything in. The differences between the PR and my implementation are:

* Independant option to replace spaces with underscores (option available in GUI)
* Home assistant option (not available in GUI) This will publish config values to the homeassistant topic in the PR you provided but will only work on Evolution and Nexus as the topics used are specific to those controllers. Evo2.0 specific topics will only be configured Evo2 controllers (ambient temp, battery charge current). This option works with or without the "replace spaces with underscore" option and with or without the presence of a user denied root topic.
* added payload_on and payload_off for binary sensor.

**Comment by lmamakos** [comment]
I believe that the auto-configuration message really only needs to be published once to configure the entities in Home Assistant.  Would it make sense to just have a companion script that could be invoked that could configure some minimal set of entities for Home Assistant, using default topics, etc?  

Anything more elaborate could continue to be implemented "manually" in the YAML configuration as it the case at present.   I was thinking that there's an "80/20" thing here, where some common, minimal subset could be useful for many.  Doing a fully generalized solution would be more complicated since in the genmqtt configuration you can turn on/off specific sets of data that get published, and you wouldn't want to auto-configure an entity in Home Assistant if the corresponding MQTT messages are not published.

**Comment by jgyates** [comment]
in the PR and in my work in progress code the config messages are only sent once per session (on connect to the MQTT server). The problem is the flexibility of the config code is very narrow. This is what the PR and my code setup:

     homeassistant/sensor/generator/line_volt/config  (Evo Nexus)
     homeassistant/sensor/generator/batt_volt/config  (Evo Nexus)
     homeassistant/sensor/generator/out_volt/config  (Evo Nexus)
     homeassistant/binary_sensor/generator/system_in_outage/config (Evo Nexus)
     homeassistant/sensor/generator/out_current/config (Evo) 
     homeassistant/sensor/generator/out_kw/config (Evo)
     homeassistant/sensor/generator/batt_charge/config (Evo 2.0)
     homeassistant/sensor/generator/ext_temp/config (Evo 2.0)
     homeassistant/sensor/generator/wifi_signal/config (Evo Nexus)

Each of these is mapped to the corresponding topic.  Due to the narrow flexibility of this config, in the current implementation I have opted to not have the home assistant setup be an option in the GUI (only enabled by editing genmqtt.conf) as this would open the door to a lot of questions like "what about this or that for a sensor instead of what you have now". This would be a moving target that would not please everyone.

Another option is that I could pull this code out in a separate script that users could feel free to edit, or they could just edit their HA config files and do this manually.

**Comment by ajsomething** [comment]
@jgyates 
The option to remove spaces in the published topics is the only required change needed, some portions of HA do not allow spaces and some do. I have found there are other ways to implement these integrations. This pull request is a result of my personal beliefs it was the only option available.
You can remove the options for publishing any Home Assistant specific MQTT messages; however please retain the ability to remove spaces for now.

@lmamakos 
You are correct, the changes in the yamal file would be better suited. And yes the published messages are required only once boot of HA. I have found the messages can basically be pasted in the Yamal file with the same results. Writing a "How-To" is better understood when the user is only working with one level of integration and configuration does not require extensive knowledge of both items.

I'm closing the pull request for the reasons above. 
Thank you all who helped.

**Comment by jgyates** [comment]
V1.14.23 with the MQTT updates to optionally remove spaces from topic path and replace the with underscores is checked into github

**Comment by liltux** [comment]
@jgyates I am trying to manipulate the data that comes from ClientInterface.py in json format.  The tough spot I am running into is the json is creating objects with keys with spaces and I am having a hard time getting JS to work around this.  I am by no means an expert, but I remembered this post.  At the time I did not see a need in no spaces with MQTT topics, as MQTT handles the spaces well.  But using json and unpacking the json is becoming a test on my part.  Just curious, how difficult would the spaces removed for MQTT be for implementing?   I am working on a work around in bash/python.

**Comment by liltux** [comment]
@jgyates a little clarification.  I am using a modified ClientInterface.py.  Using a bash script to execute the program and right now I am running the output through: tr -d "[:space:]".  The full one line in bash looks like:
python myFileVersion.py -c status_json | tr -d "[:space:]"
This returns:
{"Status":[{"Engine":[{"EngineState":"Stopped,KeySWAuto"},{"GeneratorStatus":"Stopped"},{"SwitchState":"Auto"},{"OutputPower":"0.00kW"},{"PowerFactor":"1.00"},{"RPM":"0"},{"Frequency":"0.00Hz"},{"ThrottlePosition":"0Stp"},{"CoolantTemp":"113F"},{"CoolantLevel":"643Stp"},{"OilPressure":"0psi"},{"OilTemp":"0F"},{"FuelLevel":"73"},{"OxygenSensor":"0"},{"CurrentPhaseA":"0A"},{"CurrentPhaseB":"0A"},{"CurrentPhaseC":"0A"},{"AverageCurrent":"0A"},{"VoltageA-B":"0V"},{"VoltageB-C":"0V"},{"VoltageC-A":"0V"},{"AverageVoltage":"0V"},{"AirFuelDutyCycle":"0.00"}]},{"Alarms":[{"NumberofActiveAlarms":"0"},{"NumberofAcknowledgedAlarms":"0"}]},{"Battery":[{"BatteryVoltage":"13.57V"},{"BatteryChargerCurrent":"0.00A"}]},{"Time":[{"MonitorTime":"MondayNovember9,202012:17:34"},{"GeneratorTime":"MondayNovember9,202012:17:31"}]}]}

**Comment by jgyates** [comment]
when you say "hard time getting JS to work around this" is JS javascript?

**Comment by liltux** [comment]
I was meaning JavaScript, but I am using node red as an interface so it is not just JavaScript.  in a nutshell, I want to poll the data to a database using node-red.  the easiest way for me without creating something inside of Genmon was to use bash and the ClientInterface.py program.  I am sorry I should have been clearer on that.  I am using node-red to take the json and create an object that I could pull the information from and store in a database.  I realize there are 1000 ways to do something and my method may not seem practical.  It is what came to my mind with what I know and am comfortable with.  MQTT does not let me poll and it also creates a new object for each topic, thats a mess to work through.  And SNMP may cause issues when running multiple instances from one device.  I found out you can only bind to 0.0.0.0 once. So then I was thinking if I could get one object per data command to client interface, that I would have a much easier time of getting the data I out I wanted.  I am just storing it in a simply sqlite3 database that can be then downloaded as a csv for analysis.

**Comment by jgyates** [comment]
How are you trying to dereference the object keys with spaces?
     
    If ( genmon_obj["Status"]["Engine"][“Switch State”] == “Stopped”) {
	// Do something
	}

This is off the top of my head so the format may not be exact...

Does this help?

**Pull request closed without merging**
