### PR TITLE
DietPi/NanoPi Instructions

### PR DESCRIPTION
**Pull request by skipfire**
# Pull Request Template

## Description

Readme file for getting genmon running on a NanoPi Neo running Diet Pi.  Feel free to reject, reformat, etc.

Fixes # non

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware: NanoPi Neo Air-LTS, NanoPi Neo Plus 2
* Genmon version 1.18.15

## Checklist:

- [ ] Are any new libraries required and have they been added to the install scripts
- [ ] My code follows the existing code style and formatting of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reasonably commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or errors
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tested any python code on 3.x
- [ ] I have tested any javascript on most popular browsers for compatibility
- [X] Documentation only

### CODE REVIEW

**Comment by jgyates** [comment]
Thanks, I will merge this into the wiki

**Comment by jgyates** [comment]
@skipfire 

I ordered a NanoPi Neo2 and it arrived today. My results are different from yours. This is what I did.

1) Download dietpi for the NanoPi Neo2 from here:

     https://dietpi.com/docs/hardware/#nanopi-series-friendlyarm

2) Load it on an SD card with the Raspberry Pi Imager using the option for a user specified image
3) booted the NanoPi and logged in as root, let the install finish
4) The install script informed me that the serial device was enabled and I allowed it to remain enabled
5) restarted and used dietpi-config to configure the serial port and set ttyS0 to not use the console
6) ran the genmon setup per the standard install, did not setup the serial port with the script

The script ran with no errors. One the initial start the spidev library (which is included in raspbian) was not installed so genloader installed it and it was noted in the file /var/log/genloader.log

I tested genmon with serial over IP and it worked as expected.
I tested the serial port using: sudo python3 serialtest.py /dev/ttyS0 and it passed

I have not tested any GPIO, I2C or SPI related I/O

I am not sure why our results are different.

**Comment by skipfire** [comment]
I can explain the difference in results, I'm so ingrained with the rule of doing as little as root that I didn't even consider trying to do the whole thing as root.  As for the serial port, I was testing with my HAT so I was sticking with the physical pin equivalent, which was not a necessarily valid assumption.

**Comment by jgyates** [comment]
Actually I miss spoke, I finished the install as root, rebooted, then I logged in a dietpi and ran the install so that was not the issue.

**Comment by skipfire** [comment]
I'm not sure either, especially since someone else had resolved the Cryptography issue on RPiOS with the root workaround too, maybe something else subtle is happening along the way.  Simpler is better though.

**Comment by jgyates** [comment]
when you installed dietpi did you let the dietpi install process update the OS via apt? When I logged in on first boot I logged in a the dietpi user. I saw a message on the console that said to log in a root and finish the install so I did. Once I logged in a root a scrip ran automatically that updated the OS software via apt.

**Comment by skipfire** [comment]
Yeah, it really didn't want to let me do anything until I did that.

**Pull request merged**
