### PR TITLE
Add relay board support

### PR DESCRIPTION
**Pull request by liltux**
# Pull Request Template

## Description

Add support for WaveShare RPi Relay Board

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Currently untested.  Would like review of code and will update request once tested.

**Test Configuration**:
* Firmware version:
* Hardware:

## Checklist:

- [NA ] Are any new libaries required and have they been added to the install scripts
- [Yes] My code follows the existing code style and formatting of this project
- [Yes ] I have performed a self-review of my own code
- [Yes ] I have reasonably commented my code, particularly in hard-to-understand areas
- [NO] I have made corresponding changes to the documentation
- [NOT Tested as of 1-6-21 ] My changes generate no new warnings or errors
- [YES] I have checked my code and corrected any misspellings
- [NO] I have tested any python code on 2.7 and 3.x
- [NA] I have tested any javascript on most popular browsers for compatiblity

### CODE REVIEW

**Comment by liltux** [comment]
@jgyates I just wanted to get started on this pull request.  I am making as little changes as possible.  Created a new GPIO .py file to work with the WaveShare relay board specifically.  I edited the GenLoader.py and .conf files accordingly to mimic the current gengpio.py entries.  I am only submitting for review and have not tested yet.  I plan on testing as soon as I get the board but would love to have any feedback on code issues if you or anyone sees any.

**Comment by skipfire** [comment]
@liltux why not just make the current gpio functionality with configurable pin numbers using the current GPIOs being the defaults?  Then it would not have anything specific to the waveshare board or non-waveshare use, etc.

**Comment by jgyates** [comment]
Unless I am missing something I agree with @skipfire. I can see how this is different than gengpio.py, except less functionality.  If I am missing something let me know. Is there is some additional code to be added specific to the WaveShare board to be added?

Also, for a new add on there would need to be a couple of lines in genloader.py like this one for gengpioledblink.py

     https://github.com/jgyates/genmon/blob/master/genloader.py#L432

The above referenced code adds entries into an existing genloader.conf that resides in the /etc/genmon directory.

Also, some changes to genserv.py would be needed to make it show up in the web gui, but I can make those if we decide to go with a new add on.

Between genbpio.py, gengpioin.py and gengpioledblink.py there are quite a few options. I had considered merging gengpioledblink.py and gengpio.py but was not sure about how this would affect existing users so I have opted not to change it for now.

**Comment by liltux** [comment]
@jgyates @skipfire The "affect existing users"  is what I am trying to prevent in the future.  I can edit or tweak the gengpio.py file as needed for my needs.  My concern is someone will do a software update and my changes get overwritten and no longer works.

**Comment by liltux** [comment]
@jgyates is the L# 432 needed in genload.py if I added an entry into the genloader.conf  file for the new addition?  Just curious.  And I would not need a WebUI button and could just activate manual in the genloader.conf file.

**Comment by skipfire** [comment]
@liltux adding a config with values that default to the current pin mapping should prevent impact to any current users.  gengpioin has such a setup with the bounce parameter that defaults to 200.

**Comment by liltux** [comment]
@skipfire That would still require a restructure of the gengpio.py file.  That maybe a better alternative as well.  @jgyates is the gpio pin assignments something that can be moved to the config files?  This would solve my concern, but would break anyones use of the gpio.py files currently without moving over the new config files to their working directory.

**Comment by skipfire** [comment]
I could be wrong, but I was thinking for not breaking existing users is right after the code on 83-84 so it initializes without a config, but if the config is there it then can override the settings.

```
# Evolution Air Cooled Warning GPIO 12 (pin 32)
ER_WARNING = 32
```
and then adding 
```
if os.path.isfile(os.path.join(ConfigFilePath, 'gengpioin.conf')):
    config = MyConfig(filename = os.path.join(ConfigFilePath, 'gengpioin.conf'), section = 'gengpioin', log = log)
    ...other pins...
    EN_WARNING = config.ReadValue('EN_WARNING', return_type = int, default = 32)
```

**Comment by liltux** [comment]
@skipfire I like your suggestion and removed my first proposed changes to my branch and added your suggestion.  It checks for a gengpio.conf file, if present will set what ever values I want to configure for.   The loop I am stuck on is how to assign only the gpios and functions I want and clean up the calls later in the program.  I can't be turning GPIOs High or Low if they are not assigned.  Program will crash.  I only want to use 3 outputs.  

I appreciate your thoughts and advise.  I do not have much time to work on this more now, but I am thinking of making a tuple or list of the default values and loop through the list or tuple.  For each check, to turn on or off the output, it also checks the tuple or list for values present.  If the value is not in the tuple or list then it does nothing with that output.  Thoughts?

**Comment by skipfire** [comment]
@liltux why not let it go ahead and still do the other pins?  Right now someone may not hook things up to all the pins in use, only the 3 they care about, so you could leave the other events mapped to pins that are not the 3 going to your relay and then you don't have to do any downstream cleanup.  That would also then allow support for the [8 relay hat](https://czh-labs.com/products/8-spst-no-rpi-iot-power-relay-module-for-raspberry-pi-a-3a-b-2b-3b-3b?gclid=CjwKCAjwtdeFBhBAEiwAKOIy591hCzF_y4uWKvJzCC2p8ywkVBECJL_s0DP0zpDpVM-sgHx9GdeyXxoCxvEQAvD_BwE) to configure the 8 they want, the remainder will just fire to other unattached pins.

**Comment by liltux** [comment]
@skipfire I thought on that as an approach, but it is personal preference that pins do not activate if not being used.

**Comment by liltux** [comment]
This pull is not needed.  I will be closing this branch as the hardware has a way to accommodate my needs and concerns.

**Pull request closed without merging**
