### PR TITLE
Fix #666

### LINKED ISSUE #666: Genmon triggering deprecated kernel logging
### Expected Behavior

No Logging Errors

### Actual Behavior

<pre>Feb  4 16:53:16 genmon kernel: [  127.364728] ------------[ cut here ]------------
Feb  4 16:53:16 genmon kernel: [  127.364757] WARNING: CPU: 3 PID: 474 at drivers/firmware/raspberrypi.c:233 get_throttled_show+0x6c/0x70
Feb  4 16:53:16 genmon kernel: [  127.364768] deprecated, use hwmon sysfs instead
Feb  4 16:53:16 genmon kernel: [  127.364778] Modules linked in: sha256_generic cfg80211 rfkill 8021q garp stp llc bcm2835_codec(C) v4l2_mem2mem bcm2835_v4l2(C) bcm2835_isp(C) bcm2835_mmal_vchiq(C) videobuf2_dma_contig videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 snd_bcm2835(C) videobuf2_common raspberrypi_hwmon snd_pcm videodev snd_timer mc snd vc_sm_cma(C) rpivid_mem uio_pdrv_genirq uio nvmem_rmem drm drm_panel_orientation_quirks backlight fuse ip_tables x_tables ipv6
Feb  4 16:53:16 genmon kernel: [  127.365237] CPU: 3 PID: 474 Comm: python3 Tainted: G         C        5.10.63-v7l+ #1488
Feb  4 16:53:16 genmon kernel: [  127.365243] Hardware name: BCM2711
Feb  4 16:53:16 genmon kernel: [  127.365251] Backtrace:
Feb  4 16:53:16 genmon kernel: [  127.365274] [<c0b83534>] (dump_backtrace) from [<c0b838c8>] (show_stack+0x20/0x24)
Feb  4 16:53:16 genmon kernel: [  127.365284]  r7:ffffffff r6:00000000 r5:60000013 r4:c12e6b3c
Feb  4 16:53:16 genmon kernel: [  127.365297] [<c0b838a8>] (show_stack) from [<c0b87cb4>] (dump_stack+0xcc/0xf8)
Feb  4 16:53:16 genmon kernel: [  127.365311] [<c0b87be8>] (dump_stack) from [<c0220b10>] (__warn+0xfc/0x114)
Feb  4 16:53:16 genmon kernel: [  127.365321]  r10:c33efef8 r9:00000009 r8:c09bce68 r7:000000e9 r6:00000009 r5:c09bce68
Feb  4 16:53:16 genmon kernel: [  127.365328]  r4:c0ea16d8 r3:c1205094
Feb  4 16:53:16 genmon kernel: [  127.365339] [<c0220a14>] (__warn) from [<c0b8406c>] (warn_slowpath_fmt+0xa4/0xd8)
Feb  4 16:53:16 genmon kernel: [  127.365347]  r7:000000e9 r6:c0ea16d8 r5:c1205048 r4:c0ea16b0
Feb  4 16:53:16 genmon kernel: [  127.365358] [<c0b83fcc>] (warn_slowpath_fmt) from [<c09bce68>] (get_throttled_show+0x6c/0x70)
Feb  4 16:53:16 genmon kernel: [  127.365367]  r9:c33b7e00 r8:c19b2210 r7:c28a7000 r6:c0c4d71c r5:c19b8c40 r4:c28a7000
Feb  4 16:53:16 genmon kernel: [  127.365381] [<c09bcdfc>] (get_throttled_show) from [<c0848848>] (dev_attr_show+0x28/0x54)
Feb  4 16:53:16 genmon kernel: [  127.365388]  r5:c131f4e8 r4:c283ef00
Feb  4 16:53:16 genmon kernel: [  127.365402] [<c0848820>] (dev_attr_show) from [<c04f6854>] (sysfs_kf_seq_show+0x98/0x100)
Feb  4 16:53:16 genmon kernel: [  127.365410]  r5:00001000 r4:c283ef00
Feb  4 16:53:16 genmon kernel: [  127.365421] [<c04f67bc>] (sysfs_kf_seq_show) from [<c04f48cc>] (kernfs_seq_show+0x34/0x38)
Feb  4 16:53:16 genmon kernel: [  127.365431]  r9:00000001 r8:00000000 r7:00400cc0 r6:7ffff000 r5:00001001 r4:c283ef00
Feb  4 16:53:16 genmon kernel: [  127.365443] [<c04f4898>] (kernfs_seq_show) from [<c046b11c>] (seq_read_iter+0x1a0/0x4ec)
Feb  4 16:53:16 genmon kernel: [  127.365455] [<c046af7c>] (seq_read_iter) from [<c04f4f48>] (kernfs_fop_read_iter+0x140/0x188)
Feb  4 16:53:16 genmon kernel: [  127.365464]  r10:c33efee0 r9:00000000 r8:00000000 r7:c33efef8 r6:00001001 r5:c38adcc0
Feb  4 16:53:16 genmon kernel: [  127.365470]  r4:c33b7e00
Feb  4 16:53:16 genmon kernel: [  127.365482] [<c04f4e08>] (kernfs_fop_read_iter) from [<c043e25c>] (vfs_read+0x218/0x344)
Feb  4 16:53:16 genmon kernel: [  127.365491]  r10:c33eff58 r9:00000000 r8:00000000 r7:c1205048 r6:00001001 r5:c38adcc0
Feb  4 16:53:16 genmon kernel: [  127.365497]  r4:00000000
Feb  4 16:53:16 genmon kernel: [  127.365506] [<c043e044>] (vfs_read) from [<c043e854>] (ksys_read+0x68/0xe0)
Feb  4 16:53:16 genmon kernel: [  127.365515]  r10:00001001 r9:b2105e30 r8:c38adcc0 r7:00000000 r6:00000000 r5:c38adcc3
Feb  4 16:53:16 genmon kernel: [  127.365522]  r4:c1205048
Feb  4 16:53:16 genmon kernel: [  127.365531] [<c043e7ec>] (ksys_read) from [<c043e8e4>] (sys_read+0x18/0x1c)
Feb  4 16:53:16 genmon kernel: [  127.365540]  r10:00000003 r9:c33ee000 r8:c0200204 r7:00000003 r6:00001001 r5:b06fd900
Feb  4 16:53:16 genmon kernel: [  127.365547]  r4:0000000e
Feb  4 16:53:16 genmon kernel: [  127.365558] [<c043e8cc>] (sys_read) from [<c0200040>] (ret_fast_syscall+0x0/0x28)
Feb  4 16:53:16 genmon kernel: [  127.365565] Exception stack(0xc33effa8 to 0xc33efff0)
Feb  4 16:53:16 genmon kernel: [  127.365574] ffa0:                   0000000e b06fd900 0000000e b2105e30 00001001 00000000
Feb  4 16:53:16 genmon kernel: [  127.365583] ffc0: 0000000e b06fd900 00001001 00000003 0000000e 0049be68 0049be30 0049be38
Feb  4 16:53:16 genmon kernel: [  127.365591] ffe0: 00000000 b06fbde8 00000000 b6ee8f6c
Feb  4 16:53:16 genmon kernel: [  127.365600] ---[ end trace 691c3be39817ee34 ]---
</pre>

### Steps to Reproduce (including precondition)

Run genmon on any raspberry Pi with Linux kernel 4.19 or newer and without vcgencmd installed. Newr versions of raspbian no longer come with vcgencmd since the native kernel hwmon driver exists now.

### PR DESCRIPTION
**Pull request by lps-rocks**
# Pull Request Template

## Description

Fixes #666 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested Locally on Pi 4b+ w/ Raspian 11.2 & Linux 5.10.63-v7l+

## Checklist:

- [x] My code follows the existing code style and formatting of this project
- [x] I have performed a self-review of my own code
- [x] I have reasonably commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have checked my code and corrected any misspellings
- [x] I have tested any python code on 3.x

### CODE REVIEW

**Comment by jgyates** [comment]
I have incorporated these changes but added some code to maximize compatibility with installations on older distributions.

**Comment by lps-rocks** [comment]
FYI: The logic in your fix is backwards, it should prefer the paths using /hwmon/ and only fall-back to /thermal/ when the /hwmon/ paths are not available. The old paths using /thermal/ and such are deprecated and are triggering warnings in newer versions of the Linux kernel.

**Comment by jgyates** [comment]
Can you provide more details? I can not see these messages on a pi 4 running raspbian 11 kernel version 5.10.92-v7l+. Are you referring to the check if the file exist? The code should only open the file that is present. The throttled check does what you are are suggesting checks if the file exists, checking the hwmon path first. For the thermal test I do not see any warnings.

**Comment by jgyates** [comment]
also on my test system I get this:

sudo cat /sys/class/hwmon/hwmon0/in0_lcrit_alarm
cat: /sys/class/hwmon/hwmon0/in0_lcrit_alarm: No such file or directory

**Comment by lps-rocks** [comment]
Here you're correctly preferring the hwmon driver in sysfs: https://github.com/jgyates/genmon/blob/98f2abde837c6632ed11dfd50214447e3411ba2e/genmonlib/myplatform.py#L248

Here you're still preferring the old thermal driver in sysfs which is deprecated: 
https://github.com/jgyates/genmon/blob/98f2abde837c6632ed11dfd50214447e3411ba2e/genmonlib/myplatform.py#L139

Also, try: `sudo cat /sys/class/hwmon/hwmon1/in0_lcrit_alarm` - the temperature and throttle status show up as two diff hwmon devices (not sure why it was implemented in the kernel driver that way, but it was).

**Comment by jgyates** [comment]
sudo cat /sys/class/hwmon/hwmon1/in0_lcrit_alarm 
     cat: /sys/class/hwmon/hwmon1/in0_lcrit_alarm: No such file or directory

The above code you reference does not open the devices but checks that the files exist. I am not seeing any log errors by checking if the files exists. Are you? I am assuming you are not running raspbian, but another distribution, correct? If so what specifically are you running?

**Comment by lps-rocks** [comment]
Check your system dmesg to see if it triggered the deprecated kernel warning, I get this any time I check to see if that thermal file exists - It triggers once when the sysfs call is done the first time and then requires a reboot to show up again. 

Weird, I'm not sure why `cat /sys/class/hwmon/hwmon1/in0_lcrit_alarm` is not showing up in your system, can you run `ls /sys/class/hwmon/` ?

```[  127.364728] ------------[ cut here ]------------
[  127.364757] WARNING: CPU: 3 PID: 474 at drivers/firmware/raspberrypi.c:233 get_throttled_show+0x6c/0x70
[  127.364768] deprecated, use hwmon sysfs instead
[  127.364778] Modules linked in: sha256_generic cfg80211 rfkill 8021q garp stp llc bcm2835_codec(C) v4l2_mem2mem bcm2835_v4l2(C) bcm2835_isp(C) bcm2835_mmal_vchiq(C) videobuf2_dma_contig videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 snd_bcm2835(C) videobuf2_common raspberrypi_hwmon snd_pcm videodev snd_timer mc snd vc_sm_cma(C) rpivid_mem uio_pdrv_genirq uio nvmem_rmem drm drm_panel_orientation_quirks backlight fuse ip_tables x_tables ipv6
[  127.365237] CPU: 3 PID: 474 Comm: python3 Tainted: G         C        5.10.63-v7l+ #1488
[  127.365243] Hardware name: BCM2711
[  127.365251] Backtrace:
[  127.365274] [<c0b83534>] (dump_backtrace) from [<c0b838c8>] (show_stack+0x20/0x24)
[  127.365284]  r7:ffffffff r6:00000000 r5:60000013 r4:c12e6b3c
[  127.365297] [<c0b838a8>] (show_stack) from [<c0b87cb4>] (dump_stack+0xcc/0xf8)
[  127.365311] [<c0b87be8>] (dump_stack) from [<c0220b10>] (__warn+0xfc/0x114)
[  127.365321]  r10:c33efef8 r9:00000009 r8:c09bce68 r7:000000e9 r6:00000009 r5:c09bce68
[  127.365328]  r4:c0ea16d8 r3:c1205094
[  127.365339] [<c0220a14>] (__warn) from [<c0b8406c>] (warn_slowpath_fmt+0xa4/0xd8)
[  127.365347]  r7:000000e9 r6:c0ea16d8 r5:c1205048 r4:c0ea16b0
[  127.365358] [<c0b83fcc>] (warn_slowpath_fmt) from [<c09bce68>] (get_throttled_show+0x6c/0x70)
[  127.365367]  r9:c33b7e00 r8:c19b2210 r7:c28a7000 r6:c0c4d71c r5:c19b8c40 r4:c28a7000
[  127.365381] [<c09bcdfc>] (get_throttled_show) from [<c0848848>] (dev_attr_show+0x28/0x54)
[  127.365388]  r5:c131f4e8 r4:c283ef00
[  127.365402] [<c0848820>] (dev_attr_show) from [<c04f6854>] (sysfs_kf_seq_show+0x98/0x100)
[  127.365410]  r5:00001000 r4:c283ef00
[  127.365421] [<c04f67bc>] (sysfs_kf_seq_show) from [<c04f48cc>] (kernfs_seq_show+0x34/0x38)
[  127.365431]  r9:00000001 r8:00000000 r7:00400cc0 r6:7ffff000 r5:00001001 r4:c283ef00
[  127.365443] [<c04f4898>] (kernfs_seq_show) from [<c046b11c>] (seq_read_iter+0x1a0/0x4ec)
[  127.365455] [<c046af7c>] (seq_read_iter) from [<c04f4f48>] (kernfs_fop_read_iter+0x140/0x188)
[  127.365464]  r10:c33efee0 r9:00000000 r8:00000000 r7:c33efef8 r6:00001001 r5:c38adcc0
[  127.365470]  r4:c33b7e00
[  127.365482] [<c04f4e08>] (kernfs_fop_read_iter) from [<c043e25c>] (vfs_read+0x218/0x344)
[  127.365491]  r10:c33eff58 r9:00000000 r8:00000000 r7:c1205048 r6:00001001 r5:c38adcc0
[  127.365497]  r4:00000000
[  127.365506] [<c043e044>] (vfs_read) from [<c043e854>] (ksys_read+0x68/0xe0)
[  127.365515]  r10:00001001 r9:b2105e30 r8:c38adcc0 r7:00000000 r6:00000000 r5:c38adcc3
[  127.365522]  r4:c1205048
[  127.365531] [<c043e7ec>] (ksys_read) from [<c043e8e4>] (sys_read+0x18/0x1c)
[  127.365540]  r10:00000003 r9:c33ee000 r8:c0200204 r7:00000003 r6:00001001 r5:b06fd900
[  127.365547]  r4:0000000e
[  127.365558] [<c043e8cc>] (sys_read) from [<c0200040>] (ret_fast_syscall+0x0/0x28)
[  127.365565] Exception stack(0xc33effa8 to 0xc33efff0)
[  127.365574] ffa0:                   0000000e b06fd900 0000000e b2105e30 00001001 00000000
[  127.365583] ffc0: 0000000e b06fd900 00001001 00000003 0000000e 0049be68 0049be30 0049be38
[  127.365591] ffe0: 00000000 b06fbde8 00000000 b6ee8f6c
[  127.365600] ---[ end trace 691c3be39817ee34 ]---
root@genmon:~#
```

**Comment by jgyates** [comment]
yes

     ls /sys/class/hwmon/ 
     hwmon0  hwmon1  hwmon2

how are you checking to see the thermal file exists?

**Comment by lps-rocks** [comment]
Running the same code as you in a Python shell, but it only seems to trigger for the throttle check which you did set correctly to prefer the hwmon method

okay, it looks like newer kernel versions added *another* hwmon driver supported by rPi. This is going to get more complicated. I need to figure out a better way to implement this - I think we're going to have to loop through all hwmon devices and find the right one to query for the right thing - that or just require vcgencmd to be installed to view the stats.

**Comment by jgyates** [comment]
The latest code looks in both /usr/bin and /opt/vc/bin/ for vcgencmd

Are you running raspbian or another distro? It is good to know what distros do not have vcgencmd.

**Comment by jgyates** [comment]
That library appears to call the vcgencmd binary, if it is not installed it will not work so I don't thing that will provide anything useful.

**Comment by jgyates** [comment]
I checked in an update that should help. It cycles through the /sys/class/hwmon/hwmonX folders looking for the file needed for throttling and cpu temp. 

https://github.com/jgyates/genmon/blob/cb9a4d8f7a65fa3bdd29b9efb1dc76b568a69eb8/genmonlib/myplatform.py#L265

I also found a python 2 v 3 issue in the throttle check that made it use the backup method instead of vcgencmd every time. 

https://github.com/jgyates/genmon/blob/cb9a4d8f7a65fa3bdd29b9efb1dc76b568a69eb8/genmonlib/myplatform.py#L243


Let me know if you have any issues.

**Pull request closed without merging**
